// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fptzrikqivlunvjnygxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwdHpyaWtxaXZsdW52am55Z3h1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMjQyMzAsImV4cCI6MjA2OTcwMDIzMH0.3-kp0gL5mhZOGWyej95h8ugnG9FVyfNpqWSY3dVZ6t8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});